language: python

python:
    - "2.7"
    - "3.5"

env:
    - DJANGO=django==1.6.*
    - DJANGO=django==1.7.*
    - DJANGO=django==1.8.*
    - DJANGO=django==1.9.*

install:
    - pip install -r test_requirements.txt
    - pip install $DJANGO
    - pip install coveralls

script:
    - ./runtests.py

matrix:
    exclude:
        - python: "3.4"
          env: DJANGO=django==1.4.*

after_success:
    - coveralls
